export enum OrderStatus {
  CREATED = 'CREATED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  CONFIRMED = 'CONFIRMED',
  PAYMENT_DECLINED = 'PAYMENT_DECLINED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  REFUND_REQUIRED = 'REFUND_REQUIRED',
  COMPENSATION_PENDING = 'COMPENSATION_PENDING',
  CANCELLED_REFUNDED = 'CANCELLED_REFUNDED',
}
